DROP TABLE IF EXISTS A;
DROP TABLE IF EXISTS B;

CREATE TABLE A(id INTEGER PRIMARY KEY, r INTEGER, c INTEGER, val DOUBLE);
INSERT INTO "A" VALUES(0, 0, 0, 0.1);
INSERT INTO "A" VALUES(1, 1, 0, 0.2);
INSERT INTO "A" VALUES(2, 0, 1, 0.3);
INSERT INTO "A" VALUES(3, 1, 1, 0.4);

CREATE TABLE B(id INTEGER PRIMARY KEY, r INTEGER, c INTEGER, val DOUBLE);
INSERT INTO "B" VALUES(0, 0, 0, 1.0);
INSERT INTO "B" VALUES(1, 1, 0, 2.0);
INSERT INTO "B" VALUES(2, 0, 1, 3.0);
INSERT INTO "B" VALUES(3, 1, 1, 4.0);
